# https://gohugo.io/getting-started/configuration/

title: jmssrn
baseURL: https://practical-bhabha-66a31d.netlify.app
languageCode: ko-kr
hasCJKLanguage: true

theme:
  github.com/team-durumi/tailwind-aa-theme

build:
  writeStats: true