# https://gohugo.io/getting-started/configuration/

title: jmssrn
baseURL: https://pedantic-banach-b489c5.netlify.app/
languageCode: ko-kr
hasCJKLanguage: true

theme:
  github.com/team-durumi/tailwind-aa-theme

build:
  writeStats: true