# https://gohugo.io/getting-started/configuration/

title: 일본군’위안부’연구회
baseURL: https://jmssrn.org/
defaultContentLanguage: ko
hasCJKLanguage: true
pagination.pagerSize: 5

build:
  writeStats: true

taxonomies:
  tag: tags

ignoreLogs: warning-goldmark-raw-html

security:
  funcs:
    # getCSV 함수를 명시적으로 허용 (정규식 사용)
    getCSV:
      - .*
    getJSON:
      - .*
  os:
    read:
      - .*
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*