# https://gohugo.io/getting-started/configuration/

title: jmssrn
baseURL: https://jmssrn.org/
languageCode: ko-kr
hasCJKLanguage: true

theme:
  github.com/team-durumi/tailwind-aa-theme

build:
  writeStats: true