# https://gohugo.io/getting-started/configuration/

title: 일본군’위안부’연구회
baseURL: https://jmssrn.org/
defaultContentLanguage: ko
hasCJKLanguage: true
pagination.pagerSize: 5

build:
  writeStats: true

taxonomies:
  tag: tags

ignoreLogs: warning-goldmark-raw-html