# https://gohugo.io/getting-started/configuration/

title: 일본군’위안부’연구회
baseURL: https://jmssrn.org/
languageCode: ko-kr
hasCJKLanguage: true

theme:
  github.com/team-durumi/tailwind-aa-theme

build:
  writeStats: true

taxonomies:
  category: categories