main:
  - name: 학회소개
    url: /about/
    weight: -120
  - name: 공지사항
    url: 
    weight: -110
  - name: 행사안내
    url: /tags/event/
    weight: 1
    parent: 공지사항
  - name: 보도자료
    url: /tags/news/
    weight: 2
    parent: 공지사항
  - name: 학회활동
    url: 
    weight: -100
  - name: 학술행사
    url: /tags/academic/
    weight: 1
    parent: 학회활동
  - name: 발간물
    url: /tags/publish/
    weight: 2
    parent: 학회활동
  - name: 사회참여
    url: tags/socialize/
    weight: 3
    parent: 학회활동
  - name: 회원가입
    url: https://forms.gle/VYGJMcJMt8p6TuuB9
    weight: 4                