title: 일본군’위안부’연구회
description: |
  일본군’위안부’연구회는 일본군 ‘위안부’ 문제에 대해 학술적으로 천착하며 
  일본군 ‘위안부’ 문제의 정의로운 해결을 위해 활동하고 있습니다. 
  일본군’위안부 연구회’는 2016년 1월 창립되었으며 국내외의 연구자, 활동가, 유관단체 등이 회원으로 참여하고 있습니다.
images:
  - /img/about_01.jpg

license:
  title_of_work: 일본군’위안부’연구회
  title_of_work_jp: 日本軍「慰安婦」研究会  
  title_of_work_en: Research Network on Japanese Military Sexual Slavery
  link_to_work: jmssrn.org
  createor_of_work: Team-Durumi
  link_to_creator_profile: https://github.com/team-durumi
  year_of_creation: 2021

footer:
  logo: site-feature-image.jpg
  대표전화: 02-0000-0000
  팩스: 02-0000-0000
  주소: Somewhere in Seoul
  이메일:  jmssrnetwork@gmail.com
  url: https://www.facebook.com/jmssrnetwork
  caption: Github
  github: https://www.facebook.com/jmssrnetwork
  fb: https://www.facebook.com/jmssrnetwork
  tw: 
  instagram: 
  linkedin:  
