backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/media
public_folder: /media
collections:
  - name: 'post'
    label: '공지사항'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }      
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - label: "첨부파일"
        name: "post_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true 
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '메인 상단', name: 'pinned', widget: 'boolean', default: false, hint: 'true 메인 상단 노출', required: false }
      - label: "분류"
        name: "tags"
        widget: "list"
        default: ["news"]
        hint: '보도자료 news / 행사안내 event'
      - { label: '본문', name: 'body', widget: 'markdown' }          
  - name: 'article'
    label: '학회활동'
    folder: 'content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '작성자', name: 'author', widget: 'string' }      
      - { label: '날짜', name: 'date', widget: 'datetime' }
      - { label: '요약', name: 'summary', widget: 'string', required: false }
      - label: "첨부파일"
        name: "article_materials"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: true      
      - { label: '대표이미지', name: 'image', widget: 'image', required: false }
      - { label: '메인 공개', name: 'home_sticky', widget: 'boolean', default: false, hint: 'true 메인공개', required: false }
      - { label: '메인 상단', name: 'pinned', widget: 'boolean', default: false, hint: 'true 메인 상단 노출', required: false }
      - label: "활동구분"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["academic", "publish", "socialize", "news", "event"]
        default: ["academic"]
        hint: '학술행사 academic / 발간물 publish / 사회참여 socialize / 보도자료 news / 행사안내 event'
      - { label: '본문', name: 'body', widget: 'markdown' }                  